### ISSUE TITLE
How can we detect and Estimate th distance of a  Custom object

### ISSUE THREAD

**Issue by Aryanjb** [Asadullah-Dal17/AiPhile-Mediapipe-Course-2023#2]
Hi, thank you for very useful video with a good explanation. Could you please tell me how I can do custom object detection and distance estimation of that object using a camera or image file.

Thanks in advance

**Comment by Asadullah-Dal17** [comment]
1. measure the width of an object in the real world
2. calculate the distance from the object in the real world and capture the reference image.
3. Then you can implement the triangle similarity method according to your needs.
